- name: Create synapse directory
  file:
    path: /opt/synapse
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install synapse compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/synapse/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker compose -f %s config
  notify: restart synapse

- name: Install synapse config
  template:
    src: files/homeserver.yml
    dest: /opt/synapse/homeserver.yaml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart synapse
