- name: Install calibre
  include_tasks: calibre.yml

- name: Install librespeed
  include_tasks: librespeed.yml

- name: Install nextcloud
  include_tasks: nextcloud.yml

- name: Install whoami
  include_tasks: whoami.yml
