- name: Create install directory
  file:
    path: /opt/syncthing
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"


- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/syncthing/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker compose -f %s config
  notify: restart syncthing
