haproxy:
  stats_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    61356632383432353833616431393962613037646634656133316135363465313962663061633830
    6564343466343965363233623138383961653733343834340a653563393039333764613131653735
    30636333633137636664396566623831653831646562323232656233366563656464326333336339
    3266363638356436370a323566326637356366373063643163613833636531373032313532336663
    61633261633665626364343763313361656661393466373932363165306263303937306136303937
    36626534393139353135383035383934633136363730643132333037393839373337396430333535
    39386139353935663635346561616332356534373532643765646366373563323035306466626266
    37303535663465363637653237343365333434663230356534316530376164306132613466303738
    37666163616666626334363538343933313466313433353033613766653634646239
