version: "2.3"

services:
  nextcloud:
    image: linuxserver/nextcloud:version-20.0.0
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
      - DOCKER_MODS=theorangeone/lsio-mod-more-processes:latest
    volumes:
      - "{{ app_data_dir }}/nextcloud/apps:/config/www/nextcloud/apps"
      - "{{ app_data_dir }}/nextcloud/config.php:/config/www/nextcloud/config/config.php"
      - /srv/nextcloud-data/data:/data
      - /mnt/media:/content:ro
      - /mnt/tank/files:/mnt/files
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
      - collabora
    tmpfs:
      - /config/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`intersect.jakehoward.tech`)
      - traefik.http.routers.nextcloud.tls.certresolver=le
      - traefik.http.services.nextcloud-nextcloud.loadbalancer.server.port=443
      - traefik.http.services.nextcloud-nextcloud.loadbalancer.server.scheme=https
      - traefik.http.middlewares.nextcloud-hsts.headers.stsseconds=15552000
      - traefik.http.routers.nextcloud.middlewares=nextcloud-hsts@docker

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - /mnt/tank/dbs/mariadb/nextcloud:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - /mnt/tank/dbs/redis/nextcloud:/data

  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - domain=intersect\\.jakehoward\\.tech
    labels:
      - traefik.enable=true
      - traefik.http.routers.collabora.rule=Host(`collabora.jakehoward.tech`)
      - traefik.http.routers.collabora.tls.certresolver=le
      - traefik.http.services.collabora-nextcloud.loadbalancer.server.scheme=https
