$ANSIBLE_VAULT;1.1;AES256
30386663383635396466373834626430626462383133646239616665323761383466336662663362
3732373963343133633833376330336432353734656566620a366637623761626635383365396637
61656634303235373864623431313735633665616633363531313564666230313831386236363430
6163613365393863620a336364653838633037333062336335303863623064616465313935633039
37653066386164616634633065656639343637333266356234396163623539386430653232323036
64666230396330353263383536346532333564303438346564376266653237313737386130386264
32656566643339666663616539373865613466313731363663613766653832613961313336663938
30626663663034336466626635663366333162326636363362393437383932306233326531373937
35316362366539353336336536666431363039393562633665303561363636336364393264613638
3033643736373566613838316162383739626463303532313865
