$ANSIBLE_VAULT;1.1;AES256
35363536626532316139376436633932653737643236306236323030663264336132383963366234
3064393838323564656164626134393336356364346462620a333730363761653964323637376439
39366537616633346461636338633763626131346132366634363837626531343636383362663262
6265343632303862340a363865613636613363396166346566353463353565663864653835303039
30396630306131343564363839343862666439306362313661363234366663663034653262303232
39616537313030633435316262343961343634336666636534393436353730383038316564346430
38303466303265306139663439643437383538333137386334393738306237643062376566383332
31383335333533383236316233386537366533663237313535363031613739303561663166373365
31383632316664313334663539303936383239396266623236336333666131393563656662643461
36383931353461613364373762333330383732626637346139613763616534306563663232396135
34343835346634653663623664643661626539376231396439653436393666383930343332333961
30326333306663353035363530653030646138626630656531346133656362623866306337373765
62643832353961383230626333373262643432626630653930316434663631663234
