$ANSIBLE_VAULT;1.1;AES256
37396663623335333737663732353637333533363237653532633865663063343933373566383565
6434663864643236616564623062306135326333346533620a663864326137653563656134316639
64623865656164373337626231656638386363376133666366323738386639616530353937336338
3764333064323231310a373463353764633562316233656366373561373731653836316136333730
31373734326665666462363330326161303038646363326165653366666663333836313137633161
33316130303539616337633262303731326562663932343139646463653034306562313065613137
65346539346464303438653838643939313362313437623938623938636562366561623264646538
32383432616566326466336336336537356539366563653765323039363236363738363234633633
32613330646132346364343234613765313365616230623061353764363662303236
