version: "2.3"
services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    ports:
      - 33377:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`speed.jakehoward.tech`)"
      - "traefik.http.routers.librespeed.tls.certresolver=le"
      - "traefik.http.routers.librespeed.middlewares=librespeed-auth@docker"
      - "traefik.http.middlewares.librespeed-auth.basicauth.users={{ librespeed_basicauth }}"
