gitea_internal_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62353933326630353361633130636566363334666530316233383335643230316331623431336431
  6234653733386138343066326362383064656665386230640a376138316137323161353535333831
  65666233316261326336316437343036336335363661653563323237623033633436636363376638
  3263303931373934380a653666343436626432613835386637663935336365613333373230623661
  30306565616663353838616164393263376533623063633431636533383861653033386133353838
  39656530383365316564626234343763316630333637393334343532323031623562626465306162
  39643161633939653266373033333963303366663836313239353664623930626638356237343366
  33333361363730373535373031376138393363343233373634393731613532666632643030643230
  35623761666361373630613361336630306462646330336666353963636534373138
gitea_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33303865313730666162353665376639386435323734653666376632353939346534343539346231
  3664316663663562663432633265373364666136393037650a333638666331363030336432656263
  34333566323434656534383435356362323436383339366364633931653636613566323761386463
  6163646465613661360a613138303163653063393563336136363939613635633065326263303237
  65363563613635306663316165646635613665323739303332643736383033653463396633653133
  66343130623561326337626632613136643039613466626165653134306134333036393435303738
  33313861623339623165396635623862636431666166336232646631653363363361353730386233
  38323038353639303461
gitea_lfs_jwt_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63343030636264333036376165636132306536313666313063323234653366623936636166626637
  3435646265326564366561373837663065666665373763380a633964653666383335363063373431
  37333066626434366235613535383534653533636366656635323136613234643461323637656564
  3635616436356235640a306539323331623561326435643830616135613032663265303930663964
  34376531393632653562366465323735376561333439613434303166636665326565333462313532
  3865613733383266353838366139313461613237633461646566
gitea_jwt_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65656364646434383030353165333239626166353166646436343936323235353133363130646533
  6631626263633730646531383735663337373236326330330a336131346463396365626364613664
  36363536353532633836623630323862336531336237653237363835303166646530343533323537
  3535646333646563610a323765613034383662323333336230363766313130643838623039353432
  34633332343962393438613837376632303038343762626334363939646466313138626362316334
  6636613666636338616230333839316466613365396634326562
