- name: restart grafana
  shell:
    chdir: /opt/grafana
    cmd: "{{ docker_update_command }}"

- name: restart prometheus
  shell:
    chdir: /opt/prometheus
    cmd: "{{ docker_update_command }}"

- name: reload prometheus
  shell:
    chdir: /opt/prometheus
    cmd: docker compose exec prometheus kill -HUP 1
