services:
  synapse:
    image: ghcr.io/element-hq/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/etc/homeserver.yaml
      - SYNAPSE_REPORT_STATS=yes
      - UID={{ docker_user.id }}
      - GID={{ docker_user.id }}
    volumes:
      - ./homeserver.yaml:/etc/homeserver.yaml
      - ./data:/data
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse.rule=Host(`matrix.theorangeone.net`)
    networks:
      - default
      - traefik

  db:
    image: pgautoupgrade/pgautoupgrade:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data

  admin:
    image: awesometechnologies/synapse-admin:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse-admin.rule=Host(`synapse-admin.jakehoward.tech`)
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
