$ANSIBLE_VAULT;1.1;AES256
33646631386633643030353263373030386263346138366238663861376132393930333136333733
3166393461613930356230623038363033666636356333310a313562663364383535616639356133
38353130313237643535633031303633326636656363343866633131363936366236363234363761
6262386632306439360a626433633561646633613632616364326338663261643137316339653366
34653833356131386333663163346439313265623437323532623431303034616265383363636335
31396234626639336239613030393633623033626233363030666463663062303034643762626631
34663331626564613430303966666435383966653730613939643937353962613038633534336335
33643661323062373965656538386665303537303636316330333062383935356139303134666539
36333538663366306232373939323734613537386432363862653430663038393430386362373839
35366364643766623061303661303639373032313033623831316465306265623631323764646539
63316161336430643138323165343831376136643864353032393933313764323564383338616237
37356233366635303139646131396637313636643436356664323738623532336563656533616366
30393639316363333963363638373266633261313237636633636136633932376361363562333438
32613137343735306462653266656336336537303437613764633430636135303538333962613765
30643230623437666437393332353639356133663564353862356439623936663861626531306333
62316436643439653035653731633635366430643031383638303961303162616461383234616437
36323136323464333862353337653633343538383232666261653163313830653363376532303664
33356364643430346335663633343238326662313239646261313763653464633830363330316163
35313036396330363465366239353734373961666332363937313035643064393238613966343731
33633965306639643966323837353933373362346534633135333439313731656463666162366438
64313865396365623538356564353866333830336366383666663939303966373532646164616337
39386236623037636665326130356639653066333438323433366236323231396361346536343636
626661613932333136363237373331646137
