- name: Create install directory
  file:
    path: /opt/scrutiny
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/scrutiny/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  notify: restart scrutiny
  become: true
