version: "2.3"
services:
  quassel-core:
    image: linuxserver/quassel-core:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
      - DB_BACKEND=PostgreSQL
      - DB_PGSQL_USERNAME=quassel
      - DB_PGSQL_PASSWORD=quassel
      - DB_PGSQL_HOSTNAME=db
      - DB_PGSQL_PORT=5432
      - AUTH_AUTHENTICATOR=Database
      - RUN_OPTS=--config-from-environment
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "{{ wireguard.clients.intersect.ip }}:4242:4242"

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=quassel
      - POSTGRES_PASSWORD=quassel
    volumes:
      - /mnt/tank/dbs/postgres/quassel:/var/lib/postgresql/data
