version: "2.3"

services:

  synapse:
    image: matrixdotorg/synapse:v1.21.2
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/etc/homeserver.yaml
      - SYNAPSE_REPORT_STATS=yes
      - UID=0
      - GID=0
    volumes:
      - "{{ app_data_dir }}/synapse/homeserver.yaml:/etc/homeserver.yaml"
      - "{{ app_data_dir }}/synapse:/data"
    depends_on:
      - db
    expose:
      - 8008
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse.rule=Host(`matrix.jakehoward.tech`)
      - traefik.http.routers.synapse.tls.certresolver=le
      - traefik.http.routers.synapse.entrypoints=web-secure,matrix

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /mnt/tank/dbs/postgres/synapse:/var/lib/postgresql/data
